### PR TITLE
Add strip whitespace and punctuation enrichments

### PR DESCRIPTION
**Pull request by no-reply**
This closes https://www.pivotaltracker.com/story/show/83402006

### CODE REVIEW

**Comment by anarchivist** [comment]
Looks good to me. Just to confirm are we sure want to strip punctuation from the middle of strings too? (I'm not sure that we were doing that before, which is why I ask.)

**Comment by no-reply** [comment]
I checked in with content about it seems like a :+1:.  We can always have a second enrichment that just does `#strip` and/or that does the above but leaves internal newlines.

**Comment by no-reply** [comment]
:squash:ed

**Pull request merged**
