### PR TITLE
Add legacy MD5 Minter

### PR DESCRIPTION
**Pull request by no-reply**
Submitting this for discussion.

Interested in ideas about more robust testing of edge cases for existing ID's. This needs to be able to replicate https://github.com/dpla/ingestion/blob/develop/lib/akamod/select-id.py#L55

### CODE REVIEW

**Comment by no-reply** [comment]
Discussion about OriginalRecord ids happened in slack, running from here: https://dpla.slack.com/archives/tech/p1421080663000069

**Comment by no-reply** [comment]
This is updated to serve as the main ID minter for OriginalRecords.

Given the correct provider prefix, this will generate a legacy compatible ID for most OriginalRecords, but it does not attempt to replicate IDs from the legacy edge cases (primo harvesters).

**Comment by anarchivist** [comment]
I think this looks good to me, and pending any other feedback, this looks good to :squash:

**Comment by markbreedlove** [comment]
That's great; I'm all for it.

**Comment by no-reply** [comment]
:squash:ed. Leaving the Harvester refactor in a separate commit, since it's an essentially unrelated change.

**Comment by anarchivist** [comment]
:key: :passport_control:

**Pull request merged**
