### PR TITLE
Feature/punctuation cleanup

### PR DESCRIPTION
**Pull request by no-reply**
Adds several enrichments to cleanup punctuation.

The aim is to be able to conform (at least) to the following:

Titles
--- 
 - Strip out any leading colons or semi-colons. 
 - Strip out any ending punctuation, excluding parentheses but including periods. If we could make some exceptions to the stripping of trailing periods that would be great. For example, we wouldn't strip trailing periods from subject or formats where:
   - A value ends with a space-single letter-period combination ("Smith, John Q." not "Smith, John Q") OR 
   - A value ends with a space-two letters-period combination ("Johnson, Steven, Jr." not "Johnson, Steven Jr"; "oil painting, 64 x 64 in." not "oil painting, 64 x 64 in")
   - All other punctuation within the text should stay as is.

Descriptions
---
 - Strip out any leading colons or semi-colons. 

Subjects, Formats, Creators
---
 - Strip out any leading punctuation except quotation marks.
- Strip out any ending punctuation, excluding parentheses but including periods. If we could make some exceptions to the stripping of trailing periods that would be great. For example, we wouldn't strip trailing periods from subject or formats where:
   - A value ends with a space-single letter-period combination ("Smith, John Q." not "Smith, John Q") OR 
   - A value ends with a space-two letters-period combination ("Johnson, Steven, Jr." not "Johnson, Steven Jr"; "oil painting, 64 x 64 in." not "oil painting, 64 x 64 in")

Date
---
 - Strip out trailing punctuation in this field, except for square brackets, when we're displaying the ProvidedLabel (or whatever it's called).

### CODE REVIEW

**Comment by markbreedlove** [comment]
Could there be older resources where first names are abbreviated, like "Washington, Geo." for "Washington, George"?  This would also strip "Esq."  Esquire might be obvious without the period, but "Geo" might not be.  There are probably other examples that I can't think of at the moment.

**Comment by markbreedlove** [comment]
I think this is good to go, if nobody thinks that abbreviated proper names need to be fixed, or as soon as that issue can be addressed.

**Comment by no-reply** [comment]
> Could there be older resources where first names are abbreviated, like "Washington, Geo." for "Washington, George"? 

Probably.  I'm basing this on the specifications above, and I imagine we'll catch other punctuation cleanup patterns in the future.  This gets us at least to parity with the old system.

**Comment by markbreedlove** [comment]
That's all fine, then.  I agree that it should just get us to where we were with the old system.

**Comment by no-reply** [comment]
:cool: these are three distinct enrichments in three commits, so merge at your leisure.

**Pull request merged**
