### PR TITLE
Update engine_cart to ~> 1.0.1 (fixes #8556, #8557)

### PR DESCRIPTION
**Pull request by anarchivist**
Supersedes #268.

### CODE REVIEW

**Comment by anarchivist** [comment]
Also pins `sass-rails` to `~> 4.0.5` to address a build failure seen here: https://travis-ci.org/dpla/KriKri/jobs/159334607

**Comment by moltude** [comment]
Mark, I probably missing something stupid here but I'm not able to get this to generate. Just walking through the instructions for doing a clean rebuild.

```
bundle update
rake engine_cart:clean
rake engine_cart:generate
```
but when I run 
`rake db:migrate` throws an error 

```../krikri/app/models/krikri/user.rb:6:in `<module:Krikri>': uninitialized constant User (NameError)
	from ../krikri/app/models/krikri/user.rb:2:in `<top (required)>'```


This error doesn't seem connected to your PR so I probably have some local issues that need to be addressed and someone else might be a in better position to review this PR in the very short term.

**Comment by anarchivist** [comment]
@moltude Do you still have a `spec/internal` directory?

**Comment by moltude** [comment]
@anarchivist I do

**Comment by anarchivist** [comment]
@moltude The more recent versions of  `engine_cart` change the generated app to be built in `.internal_test_app`. Can you try changing the directory and running `bundle exec rake db:migrate`?

**Comment by moltude** [comment]
I got this to work against a fresh clone. Tentatively 👍  Anyone else want to review before merging ?

**Comment by markbreedlove** [comment]
Looks fine to me. The lines that were copied from Engine Cart are quite wide, and we have tried elsewhere try to stick with and 80-character limit.  I'm not sure how common this is in Ruby apps, but there's a lot of logic now in the Gemfile, and it would be nice if a file specifying dependencies could be more data-driven. I know there may be nothing to be done about this here, and that it's Ruby code and is supposed to be evaluated as such; just observing.

**Comment by moltude** [comment]
@anarchivist We should also update the documentation that refers to `spec/internal`

**Comment by markbreedlove** [comment]
@anarchivist I think the CI tests aren't running because the last commit says `[ci skip]`

**Pull request merged**
