### PR TITLE
Asynchronous harvesters

### PR DESCRIPTION
**Pull request by no-reply**
Replaces #208. See discussion there.

4e272bd is the only commit changed from the previous discussion. It contains some YARD annotation updates, minor style changes, and **one substantial change**:

  - `#http` is cached within the `Request` instance. This should make no difference now (the connection and instance would have garbage collected at the same time anyway), but will prevent spawning multiple `Faraday` connections per `Request` if for some reason `Resquest` changes in the future. https://github.com/dpla/KriKri/compare/asynchronous-harvesters?expand=1#diff-a93afa836b08961677e7a6870c08c992R106

@anarchivist and/or @markbreedlove should sanity check that before merging.

### CODE REVIEW

**Comment by no-reply** [comment]
We should probably squash the first two commits, here, but keep my changes separate.

**Comment by anarchivist** [comment]
I'm :+1:. I'm going to ping @jambun and @marktriggs here since this is a slight tweak of their initial PR.

**Comment by marktriggs** [comment]
My only slight qualm here is that the caching change will cause a single Faraday instance to be shared by multiple threads, so we'll be reliant on Faraday being thread-safe.  A bit of Googling suggests that it probably is (https://github.com/lostisland/faraday/issues/370) but that it's a sort of "best effort" thread safety at the moment.

**Comment by no-reply** [comment]
@marktriggs maybe I'm reading this wrong, but it looks to me like there's only ever one thread (at a time) associated with each `Request` instance. Is that wrong?

**Comment by marktriggs** [comment]
Oh sorry, no, you're quite right.  I think an earlier version of this code split the threads from the requests in a slightly different way, but I was getting mixed up.

I think it's fine then!  :+1: from me :)

**Comment by no-reply** [comment]
:merge: :grey_question:

**Comment by no-reply** [comment]
:laughing:

**Pull request merged**
